# This environment should be saved using pip freez
name: hp-ml-endpoint-prod
channels:
  - default
  - conda-forge
dependencies:
  - gunicorn
  - python=3.7
  - flask
  - pandas<1
  - scikit-learn=0.22.1
  - pip
  - pip:
    - xgboost
